@startuml
abstract class client.staff.FlistTest {
+ {abstract}Flist<T> buildFlist(T)
+ void setup()
+ void test1()
}
class client.staff.FlistTestSubclass {
- FlistBuilder builder
+ FlistTestSubclass(FlistBuilder)
+ Flist<T> buildFlist(T)
}
class client.staff.FlistBuilder {
+ Flist<T> build(T)
}

client.staff.FlistTest <|-- client.staff.FlistTestSubclass
client.staff.FlistTestSubclass -right-> client.staff.FlistBuilder
@enduml
